DROP TABLE IF EXISTS CENSUS_DATA;
DROP TABLE IF EXISTS CHICAGO_PUBLIC_SCHOOLS;
DROP TABLE IF EXISTS CHICAGO_CRIME_DATA;




CREATE TABLE CENSUS_DATA (
                          COMMUNITY_AREA_NUMBER CHAR(9) NOT NULL,	
                          COMMUNITY_AREA_NAME VARCHAR(15) NOT NULL,
                          PERCENT_OF_HOUSING_CROWDED DECIMAL(10,2),
                          PERCENT_HOUSEHOLDS_BELOW_POVERTY DECIMAL(10,2),
                          PERCENT_AGED_16__UNEMPLOYED	DECIMAL(10,2),
                          PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA	DECIMAL(10,2),
                          PERCENT_AGED_UNDER_18_OR_OVER_64	DECIMAL(10,2),
                          PER_CAPITA_INCOME CHAR(9),
                          HARDSHIP_INDEX CHAR(9),
                          PRIMARY KEY (COMMUNITY_AREA_NUMBER)
                        );

CREATE TABLE CHICAGO_PUBLIC_SCHOOLS (
                            School_ID CHAR(9) NOT NULL,
                            NAME_OF_SCHOOL VARCHAR(50) NOT NULL,
                            Elementary_Middle_High_School_	CHAR(2),
                            Street_Address VARCHAR(25),
                            City VARCHAR(15),
                            State CHAR(2),
                            ZIP_Code CHAR(5),
                            Phone_Number CHAR(14),
                            Link VARCHAR(50),
                            Network_Manager VARCHAR(50),
                            Collaborative_Name VARCHAR(50),
                            Adequate_Yearly_Progress_Made_ VARCHAR(10),
                            Track_Schedule VARCHAR(10),
                            CPS_Performance_Policy_Status VARCHAR(25),	
                            CPS_Performance_Policy_Level VARCHAR(25),
                            HEALTHY_SCHOOL_CERTIFIED VARCHAR(25),
                            Safety_Icon VARCHAR(25),
                            SAFETY_SCORE INT,
                            Family_Involvement_Icon VARCHAR(10),
                            Family_Involvement_Score VARCHAR(10),
                            Environment_Icon VARCHAR(10),
                            Environment_Score INT,
                            Instruction_Icon VARCHAR(10),
                            Instruction_Score INT,
                            Leaders_Icon VARCHAR(10),
                            Leaders_Score INT,
                            Teachers_Icon VARCHAR(10),
                            Teachers_Score VARCHAR(10),
                            Parent_Engagement_Icon	VARCHAR(10),
                            Parent_Engagement_Score VARCHAR(10),
                            Parent_Environment_Icon VARCHAR(10),
                            Parent_Environment_Score VARCHAR(10),
                            AVERAGE_STUDENT_ATTENDANCE	DECIMAL(3,2),
                            Rate_of_Misconducts__per_100_students_	DECIMAL(3,2),
                            Average_Teacher_Attendance	DECIMAL(3,2),
                            Individualized_Education_Program_Compliance_Rate DECIMAL(3,2),
                            Pk_2_Literacy__ DECIMAL(3,2),
                            Pk_2_Math__ DECIMAL(3,2),
                            Gr3_5_Grade_Level_Math__ DECIMAL(3,2),
                            Gr3_5_Grade_Level_Read__ DECIMAL(3,2),
                            Gr3_5_Keep_Pace_Read__ DECIMAL(3,2),
                            Gr3_5_Keep_Pace_Math__ DECIMAL(3,2),
                            Gr6_8_Grade_Level_Math__ DECIMAL(3,2),
                            Gr6_8_Grade_Level_Read__ DECIMAL(3,2),
                            Gr6_8_Keep_Pace_Math_ DECIMAL(3,2),
                            Gr6_8_Keep_Pace_Read__ DECIMAL(3,2),
                            Gr_8_Explore_Math__ DECIMAL(3,2),
                            Gr_8_Explore_Read__ DECIMAL(3,2),
                            ISAT_Exceeding_Math__ DECIMAL(3,2),
                            ISAT_Exceeding_Reading__ DECIMAL(3,2),
                            ISAT_Value_Add_Math DECIMAL(3,2),
                            ISAT_Value_Add_Read DECIMAL(3,2),
                            ISAT_Value_Add_Color_Math VARCHAR(5),
                            ISAT_Value_Add_Color_Read VARCHAR(5),
                            Students_Taking__Algebra__ VARCHAR(5),
                            Students_Passing__Algebra__ VARCHAR(5),
                            nineth_Grade_EXPLORE_2009 VARCHAR(5),
                            nineth_Grade_EXPLORE_2010 VARCHAR(5),
                            tenth_Grade_PLAN_2009 VARCHAR(5),
                            tenth_Grade_PLAN_2010 VARCHAR(5),
                            Net_Change_EXPLORE_and_PLAN VARCHAR(5),
                            eleventh_Grade_Average_ACT_2011 VARCHAR(5),
                            Net_Change_PLAN_and_ACT VARCHAR(5),	
                            College_Eligibility__ VARCHAR(5),
                            Graduation_Rate__ VARCHAR(5),
                            College_Enrollment_Rate__ VARCHAR(5),
                            COLLEGE_ENROLLMENT	INT,
                            General_Services_Route INT,
                            Freshman_on_Track_Rate__ VARCHAR(5),
                            X_COORDINATE VARCHAR(25),
                            Y_COORDINATE VARCHAR(25),
                            Latitude VARCHAR(25),
                            Longitude VARCHAR(25),
                            COMMUNITY_AREA_NUMBER INT,	
                            COMMUNITY_AREA_NAME VARCHAR(25),
                            Ward INT,
                            Police_District INT,
                            Location VARCHAR(25),
                            PRIMARY KEY (School_ID)                           
                          );

CREATE TABLE CHICAGO_CRIME_DATA (
                    ID VARCHAR(9) NOT NULL,
                    CASE_NUMBER VARCHAR(9) NOT NULL,
                    DATE DATE,
                    BLOCK VARCHAR(25),
                    IUCR VARCHAR(9),
                    PRIMARY_TYPE VARCHAR(25),
                    DESCRIPTION VARCHAR(25),
                    LOCATION_DESCRIPTION VARCHAR(25),
                    ARREST VARCHAR(5),
                    DOMESTIC VARCHAR(5), 
                    BEAT VARCHAR(25),
                    DISTRICT VARCHAR(25),
                    WARD VARCHAR(25),
                    COMMUNITY_AREA_NUMBER VARCHAR(25),
                    FBICODE VARCHAR(25),
                    X_COORDINATE VARCHAR(25),
                    Y_COORDINATE VARCHAR(25),
                    YEAR INT,
                    LATITUDE VARCHAR(25),
                    LONGITUDE DECIMAL(10,10),
                    LOCATION DECIMAL(10,10),
                    PRIMARY KEY (ID)                    
                  );


